server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mariadb://${MYSQL_HOST:localhost}:3306/libmsdb?createDatabaseIfNotExist=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: libmsdev
    password: 123123

  mail:
    username: 'fadiftenaft@gmail.com'
    password: ''
